// Key words for characters or places.
// Take 1 or 2 characters and a place or an event
const KEYWORDS = {
  character: [
    "beast",
    "girl",
    "teen",
    "boy",
    "man",
    "men",
    "woman",
    "women",
    "king",
    "lord",
    "queen",
    "knight",
    "knights",
    "soldier",
    "astronaut",
    "dog",
    "cat",
    "wolf",
    "dragon",
    "creature",
    "deer",
    "elf",
    "dwarf",
    "wonderful girl",
    "pretty girl",
    "stunning princess",
    "princess",
    "imposing Knight",
    "imposing king",
    "whale",
    "moon",
    "sun",
    "mermaid",
    "pirat",
    "young woman",
    "young man",
    "young women",
    "young men",
    "fishman",
    "swordsman",
    "swordswoman",
    "blond Princess",
    "imposing queen",
    "mafioso",
    "wizard",
    "witch",
    "magician",
    "knightess",
    "pretty teen",
    "beautiful queen",
    "beautiful teen",
    "beautiful women",
    "pretty princess",
    "marksman",
    "markswoman",
    "sniper",
    "fairy",
    "fairies",
    "chinese women",
    "japanese women",
    "african women",
    "european women",
    "oriental women",
    "latina women",
    "chinese woman",
    "japanese woman",
    "african woman",
    "european woman",
    "oriental woman",
    "latina woman",
    "latina",
    "oriental girl",
    "chinese girl",
    "japanese girl",
    "african girl",
    "european girl",
    "latina girl",
    "blade",
    "pale woman",
    "hunter",
    "huntress",
    "archer",
    "oriental king",
    "oriental pricess",
    "templar",
    "knights",
    "warriors",
    "wolves",
    "whales",
    "flying whales",
    "warriors",
    "soldiers",
    "flying jellyfishs",
    "pianist",
    "flutist",
    "harpist",
    "pianist",
    "violonist",
    "prince",
    "oriental prince",
    "stunning prince",
    "singer",
    "assassin",
    "adventurer",
    "adventuress",
    "ninja",
    "ninjas",
    "kunoichi",
    "spy",
    "eagle",
    "chinese dragon",
    "dophin",
    "shark",
    "horse",
    "majestic horse",
    "scary shark",
    "flying whale",
    "rabbit",
    "cute rabbit",
    "wolf",
    "lion",
    "howling wolf",
    "jellyfish",
    "flying jellyfish",
    "colorful jellyfish",
    "doves",
    "robot",
    "female robot",
    "statue",
    "church",
    "house",
    "fountain",
    "servant",
    "maid",
    "roses",
    "violets",
    "cyborg",
    "female cyborg",
    "skull",
    "samurai",
    "batteman",
    "fox",
    "panda",
    "unicorn",
    "girls",
    "pretty girls",
    "wonderful girl",
    "wonderful girls",
    "girl",
    "anime girl",
    "cute girl",
    "european girl",
    "cute girl",
    "chinese girl",
    "japanese girl",
    "african girl",
    "european girl",
    "man",
    "tree",
    "cherry tree",
    "pink tree",
    "flowering tree",
    "punk",
    "car",
    "fast car",
    "woman holding umbrella",
    "pirate",
    "pirate ship",
    "sleeping girl",
    "blonde girl",
    "blonde woman",
    "blonde women",
    "brunette girl",
    "brunette woman",
    "brunette women",
    "black haired girl",
    "black haired woman",
    "black haired women",
    "katana",
    "elephant",
    "saber-toothed tiger",
    "tiger",
    "locomotive",
    "castle",
    "lighthouse",
    "butterfly",
    "dinosaur",
    "planet",
    "pet",
    "pets",
    "waterfall",
    "spartan",
    "baby",
    "animal",
    "animals",
    "owl",
    "jesus",
    "flower",
    "flowers",
    "nurse",
    "mushroom",
    "frog",
    "ghost",
    "ghosts",
    "vampire",
    "vampires",
    "bunny",
    "skull",
    "penguin",
    "alien",
    "fox",
    "golden retriever",
    "plant",
    "cowboy",
    "teacher",
    "professor",
    "scientist",
    "goth",
    "gothic",
    "wiking",
    "bear",
    "marathon",
    "marathoner",
    "fish",
    "carp",
    "dragon hunter",
    "god",
    "goddess",
    "jesus",
    "Hera",
    "Poseidon",
    "Hades",
    "Zeus",
    "Anubis",
    "Ganesh",
    "Geisha",
    "Hestia",
    "Demeter",
    "Artemis",
    "Athena",
    "Apollon",
    "Isis",
    "osiris",
    "seth",
    "horus",
    "thot",
    "pin-up",
    "neon",
    "umbrella",
    "shooting star",
    "oni mask",
    "angel",
    "army",
    "catgirl",
    "bunnygirl",
    'couple',
    'young couple'
  ],
  location: [
    "sea",
    "ocean",
    "desert",
    "mountains",
    "sky",
    "forest",
    "jungle",
    "coffee",
    "subway",
    "deep jungle",
    "city",
    "town",
    "abyss",
    "grotto",
    "subway",
    "stormy sea",
    "stormy sky",
    "sunny sky",
    "volcano",
    "snowy plain",
    "plain",
    "green plain",
    "dark forest",
    "old town",
    "futuristic city",
    "blue sky",
    "night",
    "starry sky",
    "campaign",
    "japan campaign",
    "chinese campaign",
    "chinese city",
    "toundra",
    "medieval city",
    "medieval town",
    "dawn",
    "sunset",
    "twilight",
    "river",
    "bay",
    "cliff",
    "lake",
    "thunder",
    "road",
    "wavy sea",
    "hill",
    "valley",
    "space",
    "solar system",
    'milky way',
    "traveler",
    'ruin',
    "ruins",
    "abandoned city",
    "beach"
  ],
  event: ["easter", "Great Wave off Kanagawa", "christmas", "halloween", "ramadan", "eid mubarak", "pink", "winter", "summer", "spring", "fall", "aesthetic"],
};

// Quality-boosting keyword in prompts
const BOOSTER_KEYWORDS = ["FHD", "4k", "4K", "HD", "UHD", "HQ"];

const TYPE_KEYWORD = [
  "Landscape",
  // Not currently supported by AIs
  // "Logo", "Sentence"
];

// Style indicator keyword
const STYLE_KEYWORD = [
  {
    style: "Pixel Art",
    prompt:
      "16 bit layered pixel art, many layers, infinite depth, pixels, voxels, chaotic colors, art like octopath traveler and celeste, vierbit, art by naoki ikushima and mika izuka, 4k uhd, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Anime Portrait",
    prompt:
      "by studio ghibli, portrait of an anime person, perfect symmetrical face, single portrait, aesthetic, by makoto shinkai and like demon slayer, deviantart, anime key visual, 4k uhd, trending on pixiv, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Heroic Fantasy",
    prompt:
      "by studio ghibli, landscape of an anime, aesthetic, by makoto shinkai and like demon slayer, deviantart, anime key visual, 4k uhd, trending on pixiv, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Fantasy",
    prompt:
      "by studio ghibli, landscape of an anime, aesthetic, by makoto shinkai and like demon slayer, deviantart, anime key visual, 4k uhd, trending on pixiv, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Anime Landscape",
    prompt:
      "by studio ghibli, landscape of an anime, aesthetic, by makoto shinkai and like demon slayer, deviantart, anime key visual, 4k uhd, trending on pixiv, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Digital Landscape",
    prompt:
      "stunning landscape, intricate, elegant, highly detailed, digital painting, concept art, smooth, sharp focus, illustration, art by martina stipan, andree wallin and greg rutkowski, trending on artstation, 4k, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Dark",
    prompt:
      "stunning landscape, intricate, elegant, highly detailed, dark, digital painting, concept art, smooth, sharp focus, illustration, art by tsutomu kitazawa and greg rutkowski, art like dark souls, bloodborne, elden ring, trending on artstation, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Beautiful Portrait",
    prompt:
      "alluring portrait, intricate, perfect symmetrical face, highly detailed, single portrait, digital painting, concept art, naughty, sharp focus, cinematic lighting, illustration, art by artgerm and greg rutkowski, wlop, alphonse mucha, cgsociety, trending on artstation, 4k, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Caricature",
    prompt:
      "Cartoon caricature realistic, cute as a pixar disney character caricature cute full body from up 2009 unreal engine octane render 3d render photorealistic, trending on artstation, 4k, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "CGI Character",
    prompt:
      "portrait of a CGI animation character, perfect symmetrical face, magical background, bright natural lighing, backlighting, professional studio quality, looking at camera, large round cute detailed eyes, detailed, cute, adorable, intricately detailed, fantasy art, 4k, digital painting, trending on artstation, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Cute Kawaii",
    prompt:
      "cute, tiny, little chibi, kawai, furry, great face expression, dynamic pose, cinematic, hyper realism, high detail, 4k, 8mm, octane render, bokeh, artstation, detailed character design by mark ryden and pixar, pixiv, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Vintage",
    prompt:
      "vintage, intricate, very very beautiful, retro, elegant, vintage colors, highly detailed, digital painting, artstation, 4k, concept art, soft light, smooth, sharp focus, illustration, trending on artstation, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Retro",
    prompt:
      "retro, intricate, very very beautiful, retro, elegant, retro colors, highly detailed, digital painting, artstation, concept art, 4k, soft light, smooth, sharp focus, illustration, trending on artstation, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Cyberpunk",
    prompt:
      "cyberpunk, in heavy raining futuristic cyberpunk, sci-fi, fantasy, intricate, very very beautiful, elegant, neon light, highly detailed, digital painting, artstation, concept art, soft light, smooth, sharp focus, 4k, illustration, trending on artstation, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Steampunk",
    prompt:
      "steampunk, futuristic, surrealism, dawn, sci-fi, intricate, very very beautiful, elegant, machine and cogwheels, highly detailed, digital painting, artstation, concept art, soft light, smooth, sharp focus, art by su jeong ahn, 4k, trending on artstation, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Digital Art",
    prompt:
      "intricate, elegant, highly detailed, digital painting, concept art, smooth, sharp focus, illustration, art by wlop, greg rutkowski and alexandra fomina, trending on artstation, 4k, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Digital Portrait",
    prompt:
      "digital painting portrait, natural lighting, perfect symmetrical face, in the style of pixar, sharp, art by wlop, focus art by Arthur Streeton and Božidar Jakac, trending on artstation, 4k, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Psycho",
    prompt:
      "anthropomorphic, beautiful, borderlands 3 psycho portrait, colourful vector, graphic novel, grunge, trending on artstation, 4k, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Realistic Anime Face",
    prompt:
      "face portrait, smooth soft skin, beautiful eyes, perfect symmetrical face, intricate colored hair, symmetrical, anime wide eyes, 4k, soft lighting, detailed face, by makoto shinkai and like demon slayer, stanley artgerm lau, wlop, rossdraws, concept art, digital painting, trending on artstation, most beautiful artwork in the world, masterpiece",
  },
  {
    style: "Render 3D",
    prompt:
      "highly detailed, hyperrealistic, CG render, octane, bokeh, 4k, 8mm, unreal engine 3d, most beautiful artwork in the world, masterpiece",
  },
];

module.exports = {
  KEYWORDS,
  BOOSTER_KEYWORDS,
  TYPE_KEYWORD,
  STYLE_KEYWORD,
};
